---
- hosts: solr2
  gather_facts: False
  user: root

  tasks:
  - name: Write the new ec2 instance host key to known hosts
    connection: local
    shell: "ssh-keyscan -H {{ inventory_hostname }} >> ~/.ssh/known_hosts"
  
  - name: hostname check
    shell: "hostname"
    register: hostname    

  - name: hostname-view -  Show Details
    debug: 
      msg: "{{ hostname.stdout_lines }}"    